version: '3.4'

services:
  ticketing.idp:
    image: ${DOCKER_REGISTRY-}ticketingidp
    build:
      context: .
      dockerfile: identity/Ticketing.Idp/Dockerfile

  paas.ticketing.api:
    image: ${DOCKER_REGISTRY-}paasticketingapi
    build:
      context: .
      dockerfile: Dockerfile

  paas.ticketing.apihal:
    image: ${DOCKER_REGISTRY-}paasticketingapihal
    build:
      context: .
      dockerfile: DockerfileHal

  paas.ticketing.apigraphql:
    image: ${DOCKER_REGISTRY-}paasticketingapigraphql
    build:
      context: .
      dockerfile: DockerfileGraphQL